---
- name: Checkout standard configs from GitHub
  hosts: localhost
  become: yes
  become_user: root

  roles:
    - git_checkout

# - name: Configuration management on Unix servers
#   hosts: all
#   become: yes
#   become_user: root

#   roles:
#     - config_mgmt