---
- set_fact:
    config: "{{config_file.key}}"

- name: Remove packages if packages_removed defined in standard_configs.yml for config file {{config.dest}}
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ config.packages_removed }}"
  when: config.packages_removed is defined

- name: Install packages if packages_installed defined in standard_configs.yml for config file {{config.dest}}
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ config.packages_installed }}"
  when: config.packages_installed is defined

- name: Deploy {{ config.dest }} from Version control system
  template:
    src: "{{local_tmp}}/{{ config.dest }}"
    dest: "{{ config.dest }}"
    owner: "{{ config.owner }}"
    group: "{{ config.group }}"
    mode: "{{ config.permission }}"
  notify: Restart {{ config.service }}

- name: Start {{ config.service }}
  service:
    name: "{{ config.service }}"
    state: started
    enabled: yes
    