---
- set_fact:
    configs: "{{config_file.value}}"

- name: Remove packages if packages_removed defined in standard_configs.yml for config file {{configs.dest}}
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{ configs.packages_removed }}"
  when: configs.packages_removed is defined

- name: Install packages if packages_installed defined in standard_configs.yml for config file {{configs.dest}}
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ configs.packages_installed }}"
  when: configs.packages_installed is defined

- name: Deploy {{ configs.dest }} from Version control system
  template:
    src: "{{local_tmp}}/{{ configs.dest }}"
    dest: "{{ configs.dest }}"
    owner: "{{ configs.owner }}"
    group: "{{ configs.group }}"
    mode: "{{ configs.permission }}"
  notify: Restart {{ configs.service }}

- name: Start {{ configs.service }}
  service:
    name: "{{ configs.service }}"
    state: started
    enabled: yes
    