---
- name: Import standard_configs.yml file 
  include_vars: "{{ local_tmp }}/custom_configs/standard_configs.yml"

- include_tasks: config_deploy.yml
  loop: "{{ standard_config_files|dict2items }}"
  loop_control:
    loop_var: config_file 