- name: Create tmp folder to standard configs
  local_action:
    module: file
    path: "{{ local_tmp }}"
    state: directory

- name: Install git on ansible server
  yum:
    name: git 
    state: installed

- name: Check out standard configs from github to {{ local_tmp }}
  git:
    repo: "{{standand_config_repo}}"
    dest: "{{ local_tmp }}"
    accept_hostkey: true
    force: yes