---
- name: get all installed packages info
  package_facts:
    manager: "auto"
  register: current_installed_packages

- name: listed all packages info
  debug: msg={{ current_installed_packages }}

- name: deplay package info 
  debug: msg={{ item.name}}
  with_items: "{{ current_installed_packages.ansible_facts.packages.NetworkManager }}"

# - name: add package infos into csv file
#   template:
#     src: package_info.j2
#     dest: /tmp/package_info.csv

# - name: updated packages 
#   yum:
#     name: "{{ item }}"
#     state: latest
#   with_items: "{{ list_of_packages }}"
#   register: package_updated

# - name: get latest installed packages info
#   package_facts:
#     manager: "auto"
#   register: latest_installed_packages

# - name: get defails of packages_info
#   set_fact:
#     package_update_info: ""
#   when: 
#     - item.key == current_installed_packages.ansible_facts.packages[item.key]
#     - 
#   with_items: "{{ latest_installed_packages.ansible_facts.packages }}"